# Generated by Django 3.2.19 on 2026-01-05 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='File Name')),
                ('path', models.TextField(verbose_name='File Path')),
                ('signature', models.CharField(max_length=64, verbose_name='File signature')),
                ('size', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.file')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.tag')),
            ],
            options={
                'verbose_name': 'FileTag',
                'verbose_name_plural': 'FileTag',
                'unique_together': {('file', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(related_name='File', through='house.FileTag', to='house.Tag'),
        ),
    ]
