# Generated by Django 5.2.10 on 2026-01-22 05:16

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    """Criar os grupos padrão: admin, users, guest"""
    groups = ['admin', 'users', 'guest']
    for group_name in groups:
        Group.objects.get_or_create(name=group_name)


def delete_groups(apps, schema_editor):
    """Deletar os grupos criados (reversão)"""
    Group.objects.filter(name__in=['admin', 'users', 'guest']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_tag_create_by'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
