# Generated by Django 5.2.10 on 2026-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_populate_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='visibility',
            field=models.CharField(choices=[('public', 'Público'), ('users', 'Usuários'), ('private', 'Privado')], default='users', max_length=10, verbose_name='Visibilidade do Arquivo'),
        ),
    ]
