# Generated by Django 5.2.10 on 2026-01-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_file_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
