# Generated by Django 5.2.10 on 2026-01-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_populate_tag_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='lastUsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
