# Generated by Django 5.2.10 on 2026-01-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_add_user_to_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='File Path'),
        ),
    ]
