# Generated by Django 5.2.10 on 2026-02-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_add_thumbnail_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Configuration Name')),
                ('config', models.JSONField(verbose_name='Configuration Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensão do Arquivo'),
        ),
    ]
