# Generated by Django 5.2.10 on 2026-02-02 04:20

import django.db.models.deletion
import house.models.file
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_add_ext_files_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=house.models.file.user_directory_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=house.models.file.user_thumbnail_path, verbose_name='Thumbnail'),
        ),
        migrations.CreateModel(
            name='UserProfileSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Termo Pesquisado')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Lista de tags aplicadas na busca', verbose_name='Tags Utilizadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Busca',
                'verbose_name_plural': 'Históricos de Busca',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='house_userp_user_id_335c92_idx'), models.Index(fields=['term'], name='house_userp_term_d80ca3_idx')],
            },
        ),
    ]
