# Generated by Django 5.2.10 on 2026-02-02 04:37

import house.models.extended_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_alter_file_file_alter_file_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=house.models.extended_user.user_profile_photo_path, verbose_name='Foto de Perfil'),
        ),
    ]
